### ISSUE TITLE
Invalid credentials (49) Issues

### ISSUE THREAD

**Issue by abbiewade** [glauth/glauth#251]
I've been trying to stand up `glauth` with a postgres backend using `glauth/glauth-plugins:v2.1.0-rc1` and am running into issues when trying to run an `ldapsearch`. 

As per https://github.com/glauth/glauth/issues/208, I have been running: 

`ldapsearch -LLL -H ldap://localhost:3893 -D cn=serviceuser,ou=svcaccts,dc=glauth,dc=com -w mysecret -x -bdc=glauth,dc=com cn=hackers`

Returns error `ldap_bind: Invalid credentials (49)`

And logs `WARN 010  "level"=2 "msg"="BindDN not part of our BaseDN"  "basedn"="" "binddn"="cn=serviceuser,ou=svcaccts,dc=glauth,dc=com"`

Thanks in advance.

====================================================================

My `docker-compose` is 

```
version: "3.7"

volumes:
  glauth_db:

services:
  glauth:
    image: glauth/glauth-plugins:v2.1.0-rc1
    container_name: glauth
    volumes:
      - ./config.cfg:/app/config/
    depends_on:
      - glauth_db
    ports:
      - 389:389
      - 3893:3893
      - 636:636

  glauth_db:
    container_name: glauth_db
    image: postgres:12-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: glauth
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: glauth
    volumes:
      - glauth_db:/var/lib/postgresql/data
    ports:
      - 5432:5432
```

My `config.cfg` file is: 
```
        debug = true
        [ldap]
          enabled = true
          listen = "0.0.0.0:3893"
        [ldaps]
          enabled = false
          listen = "0.0.0.0:3894"
          cert = "/app/config/certs/cert"
          key = "/app/config/certs/cert.key"
        [backend]
          datastore = "plugin"
          plugin = "postgres.so"
          pluginhandler = "NewPostgresHandler"
          database = "postgres://glauth:secret@glauth_db:5432/glauth?sslmode=disable"
        [behaviors]
          IgnoreCapabilities = false
          LimitFailedBinds = true
          NumberOfFailedBinds = 3
          PeriodOfFailedBinds = 10
          BlockFailedBindsFor = 60
          PruneSourceTableEvery = 600
          PruneSourcesOlderThan = 600
        [api]
          enabled = false
```

I have populated the database with [this sql](https://glauth.github.io/docs/databases.html): 
```
INSERT INTO groups(name, gidnumber) VALUES
  ('superheros', 5501),
  ('svcaccts', 5502),
  ('civilians', 5503),
  ('caped', 5504),
  ('lovesailing', 5505),
  ('smoker', 5506);

INSERT INTO includegroups(parentgroupid, includegroupid) VALUES
  (5503, 5501),
  (5504, 5502),
  (5504, 5501);

INSERT INTO users(name, uidnumber, primarygroup, passsha256) VALUES
  ('hackers', 5001, 5501,'6478579e37aff45f013e14eeb30b3cc56c72ccdc310123bcdf53e0333e3f416a'),
  ('johndoe', 5002, 5502,'6478579e37aff45f013e14eeb30b3cc56c72ccdc310123bcdf53e0333e3f416a'),
  ('serviceuser', 5003, 5502, '652c7dc687d98c9889304ed2e408c74b611e86a40caa51c4b43f1dd5913c5cd0');

INSERT INTO users(name, uidnumber, primarygroup, passsha256, othergroups) VALUES
  ('user4', 5004, 5504,'652c7dc687d98c9889304ed2e408c74b611e86a40caa51c4b43f1dd5913c5cd0','5505,5506');

INSERT INTO capabilities(userid, action, object) VALUES
  (5001, 'search', 'ou=superheros,dc=glauth,dc=com'),
  (5003, 'search', '*');
```
