### ISSUE TITLE
macOS native binary run with postgres plugin throwing error: "error"="Unable to load specified backend plugin: plugin: not implemented" "msg"="Could not create server"

### ISSUE THREAD

**Issue by leopku** [glauth/glauth#265]
OS: macOS Big Sur (11.16.5)
glauth version: v2.1.0 (downloaded from release)
plugin: postgres.so

config:

```
[backend]
  datastore = "plugin"
  # If "plugin," uncomment the line below
  # plugin = "bin/sqlite.so"
  # pluginhandler = "NewSQLiteHandler"
  plugin = "postgres.so"
  pluginhandler = "NewPostgresHandler"
```

files:

$ ls
```
glauth*              glauth.sha256        mysql.so             postgres.so          sample-database.cfg  sqlite.so
```

```
./glauth -c sample-database.cfg
09:38:20.886567 doConfig ▶ DEBU 001  "level"=6 "msg"="Debugging enabled"
09:38:20.886598 startService ▶ DEBU 002  "level"=6 "msg"="Web API enabled"
09:38:20.886635 startService ▶ ERRO 003  "error"="Unable to load specified backend plugin: plugin: not implemented" "msg"="Could not create server"
```

**Comment by Fusion** [comment]
It looks like there a cgo-related issue here. I'm going to look into it.

**Comment by leopku** [comment]
BTW: any documents for plugins? 

I made plugin but got errors.

```
$ make plugins
make: *** No rule to make target `pkg/plugins/mysql.go', needed by `bin/linuxamd64/mysql.so'.  Stop.
```

Same OS (macOS 11.6.5) as above.

**Comment by Fusion** [comment]
Please re-download from the release page. I believe I fixed the issue. Note that you are also getting some nightly fixes in these updated packages.

**Comment by leopku** [comment]
@Fusion thanks for your reply.

This time error changed: `plugin was built with a different version of package net`

```shell
./glauth -c sample-database.cfg
21:59:57.090778 doConfig ▶ DEBU 001  "level"=6 "msg"="Debugging enabled"
21:59:57.090813 startService ▶ DEBU 002  "level"=6 "msg"="Web API enabled"
21:59:57.091044 RunAPI ▶ NOTI 003  "level"=3 "msg"="Starting HTTP server"  "address"="0.0.0.0:5555"
21:59:57.097929 startService ▶ ERRO 004  "error"="Unable to load specified backend plugin: plugin.Open(\"postgres\"): plugin was built with a different version of package net" "msg"="Could not create server"
```

**Comment by Fusion** [comment]
Silly question I know but did you make sure that you were using the binary and plugin from the same archive?

**Comment by Fusion** [comment]
So, did you provide the new version in the configuration file?

**Comment by leopku** [comment]
Two folders had same files as below and each folder had an independent configuration file - `sample-database.cfg`.
```
glauth*              glauth.sha256        mysql.so             postgres.so          sample-database.cfg  sqlite.so
```

and the content of configuration was:
```toml
#################
# glauth.conf

#################
# General configuration.
debug = true
# syslog = true
#
# Enable hot-reload of configuration on changes
# - does NOT work [ldap], [ldaps], [backend] or [api] sections
# watchconfig = true

#################
# yubikeyclientid = "yubi-api-clientid"
# yubikeysecret = "yubi-api-secret"

#################
# Server configuration.
#
# This is the old server-config format
# - will still work, but please use new format, shown below
#
# [frontend]
#   listen = "localhost:8484"
#   tls = false
#   cert ="certs/server.crt"
#   key = "certs/server.key"

# This ([ldap] and [ldaps]) is the new server-config format
[ldap]
  enabled = true
  listen = "0.0.0.0:3893"

[ldaps]
  enabled = false
  listen = "0.0.0.0:3894"
  cert = "certs/server.crt"
  key = "certs/server.key"

#################
# The backend section controls the data store.
[backend]
  datastore = "plugin"
  # If "plugin," uncomment the line below
  # plugin = "bin/sqlite.so"
  # pluginhandler = "NewSQLiteHandler"
  plugin = "postgres.so"
  pluginhandler = "NewPostgresHandler"
  baseDN = "dc=glauth,dc=com"

  # // MySQL //
  # Uncomment this line to configure your MySQL database connection string:
  # database = "glauth:glauth@tcp(127.0.0.1:3306)/glauth"
  # Creating database:
  #     create database glauth identified;
  #     grant all on glauth.* to glauth@localhost identified by 'glauth';
  # // Postgres //
  # Uncomment this line to configure your Postgres database connection string:
  database = "host=192.168.1.xxx port=5432 dbname=mydb user=myname password=mypasswd sslmode=disable"
  # Creating database:
  #     CREATE DATABASE <dbname>;
  #     CREATE USER <username> WITH PASSWORD '<userpassword>'
  #     GRANT ALL PRIVILEGES ON DATABASE <dbname> to <username>;
  # // SQLite //
  # Uncomment this line to configure your SQLite database connection string:
  # database = "gl.db"

  ## Configure dn format to use structures like
  ## "uid=serviceuser,cn=svcaccts,$BASEDN" instead of "cn=serviceuser,ou=svcaccts,$BASEDN"
  ## to help ease migrations from other LDAP systems
  nameformat = "cn"
  groupformat = "ou"

  ## Configure ssh-key attribute name, default is 'sshPublicKey'
  # sshkeyattr = "ipaSshPubKey"

#################
# Enable and configure the optional REST API here.
[api]
  enabled = true
  tls = false # enable TLS for production!!
  listen = "0.0.0.0:5555"
  cert = "cert.pem"
  key = "key.pem"
```
