### ISSUE TITLE
Insufficient Access Rights after update to 2.1.0

### ISSUE THREAD

**Issue by c10l** [glauth/glauth#268]
I have `glauth` running as a backend to Authelia on my home lab.

I've been running 2.0.0 for about a year with no issues. When I upgrade to 2.1.0, with no other changes, I get an `Insufficient Access Rights` error:

```
glauth_1    | 09:29:45.840709 doConfig ▶ DEBU 001  "level"=6 "msg"="Debugging enabled"  
glauth_1    | 09:29:45.840747 NewServer ▶ NOTI 002  "level"=3 "msg"="Loading backend"  "datastore"="config" "position"=0
glauth_1    | 09:29:45.840770 ListenAndServe ▶ NOTI 003  "level"=3 "msg"="LDAP server listening"  "address"="0.0.0.0:3893"
glauth_1    | 09:30:02.195159 Bind ▶ DEBU 004  "level"=6 "msg"="Bind request"  "basedn"="dc=c10l,dc=cc" "binddn"="cn=c10l,dc=c10l,dc=cc" "src"={"IP":"172.21.0.3","Port":43348,"Zone":""}
glauth_1    | 09:30:02.195212 Bind ▶ DEBU 005  "level"=6 "msg"="Bind success"  "binddn"="cn=c10l,dc=c10l,dc=cc" "src"={"IP":"172.21.0.3","Port":43348,"Zone":""}
glauth_1    | 09:30:02.195881 Search ▶ DEBU 006  "level"=6 "msg"="Search request"  "basedn"="dc=c10l,dc=cc" "binddn"="cn=c10l,dc=c10l,dc=cc" "filter"="(uid=c10l)" "scope"=2 "searchbasedn"="dc=c10l,dc=cc" "src"={"IP":"172.21.0.3","Port":43348,"Zone":""}
glauth_1    | 2022/07/01 09:30:02 handleSearchRequest error LDAP Result Code 50 "Insufficient Access Rights": Search Error: no capability allowing BindDN cn=c10l,dc=c10l,dc=cc to perform search in dc=c10l,dc=cc
```

I tried adding capabilities to the user, but it didn't help:

```
    [[users.capabilities]]
    action = "search"
    object = "dc=c10l,dc=cc"
```

Setting `IgnoreCapabilities = true` makes it work again, so my capabilities configuration must be wrong, or I'm missing something else in the config.

Downgrading back to 2.0.0 solves the issue. Here's a log for the same login attempt on 2.0.0:

```
glauth_1    | 09:28:11.360188 doConfig ▶ DEBU 001  "level"=6 "msg"="Debugging enabled"
glauth_1    | 09:28:11.360328 NewServer ▶ NOTI 002  "level"=3 "msg"="Loading backend"  "datastore"="config" "position"=0
glauth_1    | 09:28:11.360381 ListenAndServe ▶ NOTI 003  "level"=3 "msg"="LDAP server listening"  "address"="0.0.0.0:3893"
glauth_1    | 09:28:16.309683 isInTimeout ▶ DEBU 004  "level"=6 "msg"="CFRDBG: Created Struct"  "remoteAddr"="172.21.0.3"
glauth_1    | 09:28:16.309806 Bind ▶ DEBU 005  "level"=6 "msg"="Bind request"  "basedn"="dc=c10l,dc=cc" "binddn"="cn=c10l,dc=c10l,dc=cc" "src"={"IP":"172.21.0.3","Port":43342,"Zone":""}
glauth_1    | 09:28:16.309846 Bind ▶ DEBU 006  "level"=6 "msg"="Bind success"  "binddn"="cn=c10l,dc=c10l,dc=cc" "src"={"IP":"172.21.0.3","Port":43342,"Zone":""}
glauth_1    | 09:28:16.310095 Search ▶ DEBU 007  "level"=6 "msg"="Search request"  "basedn"="dc=c10l,dc=cc" "binddn"="cn=c10l,dc=c10l,dc=cc" "filter"="(uid=c10l)" "scope"=2 "searchbasedn"="dc=c10l,dc=cc" "src"={"IP":"172.21.0.3","Port":43342,"Zone":""}
glauth_1    | 09:28:16.310142 Search ▶ DEBU 008  "level"=6 "msg"="AP: Search OK"  "filter"="(uid=c10l)"
glauth_1    | 09:28:16.310837 Bind ▶ DEBU 009  "level"=6 "msg"="Bind request"  "basedn"="dc=c10l,dc=cc" "binddn"="cn=c10l,ou=admins,dc=c10l,dc=cc" "src"={"IP":"172.21.0.3","Port":43344,"Zone":""}
glauth_1    | 09:28:16.310873 Bind ▶ DEBU 00a  "level"=6 "msg"="Bind success"  "binddn"="cn=c10l,ou=admins,dc=c10l,dc=cc" "src"={"IP":"172.21.0.3","Port":43344,"Zone":""}
glauth_1    | 09:28:16.321437 Bind ▶ DEBU 00b  "level"=6 "msg"="Bind request"  "basedn"="dc=c10l,dc=cc" "binddn"="cn=c10l,dc=c10l,dc=cc" "src"={"IP":"172.21.0.3","Port":43346,"Zone":""}
glauth_1    | 09:28:16.321488 Bind ▶ DEBU 00c  "level"=6 "msg"="Bind success"  "binddn"="cn=c10l,dc=c10l,dc=cc" "src"={"IP":"172.21.0.3","Port":43346,"Zone":""}
glauth_1    | 09:28:16.321702 Search ▶ DEBU 00d  "level"=6 "msg"="Search request"  "basedn"="dc=c10l,dc=cc" "binddn"="cn=c10l,dc=c10l,dc=cc" "filter"="(uid=c10l)" "scope"=2 "searchbasedn"="dc=c10l,dc=cc" "src"={"IP":"172.21.0.3","Port":43346,"Zone":""}
glauth_1    | 09:28:16.321974 Search ▶ DEBU 00e  "level"=6 "msg"="AP: Search OK"  "filter"="(uid=c10l)"
glauth_1    | 09:28:16.322245 Search ▶ DEBU 00f  "level"=6 "msg"="Search request"  "basedn"="dc=c10l,dc=cc" "binddn"="cn=c10l,dc=c10l,dc=cc" "filter"="(member=cn=c10l,ou=admins,dc=c10l,dc=cc)" "scope"=2 "searchbasedn"="ou=groups,dc=c10l,dc=cc" "src"={"IP":"172.21.0.3","Port":43346,"Zone":""}
glauth_1    | 09:28:16.322289 Search ▶ DEBU 010  "level"=6 "msg"="AP: Search OK"  "filter"="(member=cn=c10l,ou=admins,dc=c10l,dc=cc)"
```

**Comment by Fusion** [comment]
Do you mind sending to me your configuration file? Of course feel free to redact the accounts' credentials -> chris [at] zteo.com

**Comment by c10l** [comment]
I've just sent you an email with the config. Thanks for looking!

**Comment by Fusion** [comment]
Not sure how the query was originally failing for you. What I did was edit your file to:
- set the user's password,
- ignore capabilities
- and edit the object entry to `dc=c10l,dc=cc` (you had included the user cn in there, I removed it)

Then, this command worked:

```
ldapsearch -LLL -H ldap://localhost:3893 -D "cn=c10l,dc=c10l,dc=cc" -w dogood -x -bdc=c10l,dc=cc cn=c10l
```

**Comment by c10l** [comment]
Thanks for looking. I tried the same `ldapsearch` and can confirm it works. I checked Authelia's config but couldn't find anything glaring. In the end, I had to add individual capabilities for both `dc=foo,dc=bar` *and* `ou=groups,dc=foo,dc=bar`.

If either of those are missing, the binding is not allowed on one or the other object.

Thaks for your help, it set me in the right track!

**Comment by onedr0p** [comment]
Hi, I am trying to set up glauth with authelia as well. I am not really following what you were all able to do to make it working. Do you have any tips?

## glauth configuration

I am testing, the password decrypted is `none`

```toml
debug = true
[ldap]
    enabled = true
    listen = "0.0.0.0:3893"
[ldaps]
    enabled = false
[api]
    enabled = true
    tls = false
    listen = "0.0.0.0:5555"
[backend]
    datastore = "config"
    baseDN = "dc=home,dc=arpa"
    nameformat = "cn"
    groupformat = "ou"
[[groups]]
    name = "svc"
    gidnumber = 5500
[[users]]
    name = "admin"
    uidnumber = 5000
    primarygroup = 5500
    passsha256 = "140bedbf9c3f6d56a9846d2ba7088798683f4da0c248231336e6a05679e4fdfe"
[[users.capabilities]]
    action = "search"
    object = "*"
[[groups]]
    name = "users"
    gidnumber = 6500
[[users]]
    name = "devin"
    uidnumber = 6000
    primarygroup = 6500
    passsha256 = "140bedbf9c3f6d56a9846d2ba7088798683f4da0c248231336e6a05679e4fdfe"
```

## authelia configuration

```yaml
authentication_backend:
  password_reset:
    disable: true
  ldap:
    url: ldap://glauth:3893
    username_attribute: uid
    additional_users_dn: ou=users
    users_filter: (&({username_attribute}={input})(objectClass=person))
    additional_groups_dn: ou=groups
    groups_filter: (&(uniqueMember={dn})(objectClass=groupOfUniqueNames))
    group_name_attribute: cn
    mail_attribute: mail
    display_name_attribute: displayName
    password: none
    base_dn: dc=home,dc=arpa
    user: cn=admin,ou=svc,dc=home,dc=arpa
```

## glauth logs

```
glauth-546b97c79-l5mgx glauth 14:32:14.651356 Bind ▶ DEBU 00b  "level"=6 "msg"="Bind request"  "basedn"="dc=home,dc=arpa" "binddn"="cn=admin,ou=svc,dc=home,dc=arpa" "src"={"IP":"10.42.152.197","Port":51428,"Zone":""}
glauth-546b97c79-l5mgx glauth 14:32:14.651514 Bind ▶ DEBU 00c  "level"=6 "msg"="Bind success"  "binddn"="cn=admin,ou=svc,dc=home,dc=arpa" "src"={"IP":"10.42.152.197","Port":51428,"Zone":""}
glauth-546b97c79-l5mgx glauth 14:32:14.654708 Search ▶ DEBU 00d  "level"=6 "msg"="Search request"  "basedn"="dc=home,dc=arpa" "binddn"="cn=admin,ou=svc,dc=home,dc=arpa" "filter"="(\u0026(uid=devin)(objectClass=person))" "scope"=2 "searchbasedn"="ou=users,dc=home,dc=arpa" "src"={"IP":"10.42.152.197","Port":51428,"Zone":""}
glauth-546b97c79-l5mgx glauth 14:32:14.654943 searchMaybeTopLevelUsersNode ▶ DEBU 00e  "level"=6 "msg"="Search request"  "special case"="top-level users node"
glauth-546b97c79-l5mgx glauth 14:32:14.655255 searchMaybeTopLevelUsersNode ▶ DEBU 00f  "level"=6 "msg"="AP: Top-Level Users Browse OK"  "filter"="(\u0026(uid=devin)(objectClass=person))"
```

## authelia logs

```
authelia-56985d8557-q29b7 authelia time="2022-07-24T13:32:26Z" level=error msg="Unsuccessful 1FA authentication attempt by user 'devin': user not found" method=POST path=/api/firstfactor remote_ip=192.168.1.100 stack="github.com/authelia/authelia/v4/internal/handlers/response.go:233           markAuthenticationAttempt\ngithub.com/authelia/authelia/v4/internal/handlers/handler_firstfactor.go:53 FirstFactorPOST.func1\ngithub.com/authelia/authelia/v4/internal/middlewares/bridge.go:54           (*BridgeBuilder).Build.func1.1\ngithub.com/authelia/authelia/v4/internal/middlewares/headers.go:25          SecurityHeadersCSPNone.func1\ngithub.com/authelia/authelia/v4/internal/middlewares/headers.go:35          SecurityHeadersNoStore.func1\ngithub.com/authelia/authelia/v4/internal/middlewares/headers.go:16          SecurityHeaders.func1\ngithub.com/fasthttp/router@v1.4.10/router.go:414                            (*Router).Handler\ngithub.com/valyala/fasthttp@v1.38.0/http.go:153                             (*Response).StatusCode\ngithub.com/authelia/authelia/v4/internal/middlewares/metrics.go:22          NewMetricsRequest.func1.1\ngithub.com/valyala/fasthttp@v1.38.0/server.go:2308                          (*Server).serveConn\ngithub.com/valyala/fasthttp@v1.38.0/workerpool.go:224                       (*workerPool).workerFunc\ngithub.com/valyala/fasthttp@v1.38.0/workerpool.go:196                       (*workerPool).getCh.func1\nruntime/asm_amd64.s:1571                                                    goexit"
```
