### ISSUE TITLE
Hi 👋🏼  I am trying to set up glauth with authelia as well. I am not really following what you were all able to do to make it working. Do you have any tips? Thanks!

### ISSUE THREAD

**Issue by Fusion** [glauth/glauth#273]
Hi 👋🏼  I am trying to set up glauth with authelia as well. I am not really following what you were all able to do to make it working. Do you have any tips? Thanks!

## glauth configuration

I am testing, the password decrypted is `none`

```toml
debug = true
[ldap]
    enabled = true
    listen = "0.0.0.0:3893"
[ldaps]
    enabled = false
[api]
    enabled = true
    tls = false
    listen = "0.0.0.0:5555"
[backend]
    datastore = "config"
    baseDN = "dc=home,dc=arpa"
    nameformat = "cn"
    groupformat = "ou"
[[groups]]
    name = "svc"
    gidnumber = 5500
[[users]]
    name = "admin"
    uidnumber = 5000
    primarygroup = 5500
    passsha256 = "140bedbf9c3f6d56a9846d2ba7088798683f4da0c248231336e6a05679e4fdfe"
[[users.capabilities]]
    action = "search"
    object = "*"
[[groups]]
    name = "users"
    gidnumber = 6500
[[users]]
    name = "devin"
    uidnumber = 6000
    primarygroup = 6500
    passsha256 = "140bedbf9c3f6d56a9846d2ba7088798683f4da0c248231336e6a05679e4fdfe"
```

## authelia configuration

```yaml
authentication_backend:
  password_reset:
    disable: true
  ldap:
    url: ldap://glauth:3893
    username_attribute: uid
    additional_users_dn: ou=users
    users_filter: (&({username_attribute}={input})(objectClass=person))
    additional_groups_dn: ou=groups
    groups_filter: (&(uniqueMember={dn})(objectClass=groupOfUniqueNames))
    group_name_attribute: cn
    mail_attribute: mail
    display_name_attribute: displayName
    password: "none"
    base_dn: dc=home,dc=arpa
    user: cn=admin,ou=svc,dc=home,dc=arpa
```

## glauth logs

```
glauth-546b97c79-l5mgx glauth 14:32:14.651356 Bind ▶ DEBU 00b  "level"=6 "msg"="Bind request"  "basedn"="dc=home,dc=arpa" "binddn"="cn=admin,ou=svc,dc=home,dc=arpa" "src"={"IP":"10.42.152.197","Port":51428,"Zone":""}
glauth-546b97c79-l5mgx glauth 14:32:14.651514 Bind ▶ DEBU 00c  "level"=6 "msg"="Bind success"  "binddn"="cn=admin,ou=svc,dc=home,dc=arpa" "src"={"IP":"10.42.152.197","Port":51428,"Zone":""}
glauth-546b97c79-l5mgx glauth 14:32:14.654708 Search ▶ DEBU 00d  "level"=6 "msg"="Search request"  "basedn"="dc=home,dc=arpa" "binddn"="cn=admin,ou=svc,dc=home,dc=arpa" "filter"="(\u0026(uid=devin)(objectClass=person))" "scope"=2 "searchbasedn"="ou=users,dc=home,dc=arpa" "src"={"IP":"10.42.152.197","Port":51428,"Zone":""}
glauth-546b97c79-l5mgx glauth 14:32:14.654943 searchMaybeTopLevelUsersNode ▶ DEBU 00e  "level"=6 "msg"="Search request"  "special case"="top-level users node"
glauth-546b97c79-l5mgx glauth 14:32:14.655255 searchMaybeTopLevelUsersNode ▶ DEBU 00f  "level"=6 "msg"="AP: Top-Level Users Browse OK"  "filter"="(\u0026(uid=devin)(objectClass=person))"
```

## authelia logs

```
authelia-56985d8557-q29b7 authelia time="2022-07-24T13:32:26Z" level=error msg="Unsuccessful 1FA authentication attempt by user 'devin': user not found" method=POST path=/api/firstfactor remote_ip=192.168.1.100 stack="github.com/authelia/authelia/v4/internal/handlers/response.go:233           markAuthenticationAttempt\ngithub.com/authelia/authelia/v4/internal/handlers/handler_firstfactor.go:53 FirstFactorPOST.func1\ngithub.com/authelia/authelia/v4/internal/middlewares/bridge.go:54           (*BridgeBuilder).Build.func1.1\ngithub.com/authelia/authelia/v4/internal/middlewares/headers.go:25          SecurityHeadersCSPNone.func1\ngithub.com/authelia/authelia/v4/internal/middlewares/headers.go:35          SecurityHeadersNoStore.func1\ngithub.com/authelia/authelia/v4/internal/middlewares/headers.go:16          SecurityHeaders.func1\ngithub.com/fasthttp/router@v1.4.10/router.go:414                            (*Router).Handler\ngithub.com/valyala/fasthttp@v1.38.0/http.go:153                             (*Response).StatusCode\ngithub.com/authelia/authelia/v4/internal/middlewares/metrics.go:22          NewMetricsRequest.func1.1\ngithub.com/valyala/fasthttp@v1.38.0/server.go:2308                          (*Server).serveConn\ngithub.com/valyala/fasthttp@v1.38.0/workerpool.go:224                       (*workerPool).workerFunc\ngithub.com/valyala/fasthttp@v1.38.0/workerpool.go:196                       (*workerPool).getCh.func1\nruntime/asm_amd64.s:1571                                                    goexit"
```

## `ldapsearch`

```
❯ ldapsearch -LLL -H ldap://10.42.173.35:3893 -D "cn=admin,dc=home,dc=arpa" -w none -x -bdc=home,dc=arpa cn=devin
dn: cn=devin,ou=users,ou=users,dc=home,dc=arpa
cn: devin
uid: devin
ou: users
uidNumber: 6000
accountStatus: active
objectClass: posixAccount
objectClass: shadowAccount
loginShell: /bin/bash
homeDirectory: /home/devin
description: devin
gecos: devin
gidNumber: 6500
memberOf: ou=users,ou=groups,dc=home,dc=arpa
shadowExpire: -1
shadowFlag: 134538308
shadowInactive: -1
shadowLastChange: 11000
shadowMax: 99999
shadowMin: -1
shadowWarning: 7
```

```
❯ ldapsearch -x -D "cn=admin,ou=svc,dc=home,dc=arpa" \
                 -W -H ldap://10.42.173.35:3893 -b "ou=users,dc=home,dc=arpa" \
                 -s sub "uid=devin" --filter "(&({username_attribute}={input})(objectClass=person))"
Enter LDAP Password:
# extended LDIF
#
# LDAPv3
# base <ou=users,dc=home,dc=arpa> with scope subtree
# filter: uid=devin
# requesting: --filter (&({username_attribute}={input})(objectClass=person))
#

# devin, users, users, home.arpa
dn: cn=devin,ou=users,ou=users,dc=home,dc=arpa

# search result
search: 2
result: 0 Success

# numResponses: 2
# numEntries: 1
```

_Originally posted by @onedr0p in https://github.com/glauth/glauth/issues/268#issuecomment-1193330459_

**Comment by Fusion** [comment]
@onedr0p it appears that the objectClass is the issue. Try updating your configuration to use:

```
    users_filter: (&({username_attribute}={input})(objectClass=posixAccount))
```

**Comment by onedr0p** [comment]
Thanks that was it!

**Comment by toboshii** [comment]
Heyo, I'm working on setting up this combo as well and while the suggested changes fix user logins, I noticed a strange issue while trying to get groups working.

I initially had the group filter set to `"(&(uniqueMember={dn})(objectClass=posixGroup))"` but it wasn't working even though that seems correct at first. Taking a deeper look I discovered `uniqueMember` on groups is incomplete?

Example, when I query for a user I get an expected response:
```
dn: cn=toboshii,ou=people,ou=users,dc=example,dc=com
cn: toboshii
uid: toboshii
givenName: Toboshii
sn: Nakama
ou: people
...
memberOf: ou=media-admins,ou=groups,dc=example,dc=com
```
But when I query for a group that user is a member of:
```
dn: ou=media-admins,ou=users,dc=example,dc=com
cn: media-admins
uid: media-admins
description: media-admins
gidNumber: 5509
uniqueMember: cn=toboshii,ou=people,dc=example,dc=com
memberUid: toboshii
objectClass: posixGroup
objectClass: top
```
Why is the FDN in uniqueMember missing the `users` ou? Sure I can get it to work by changing the query to match on `memberUid` instead...but I see this is a problem going forward as most software is going to assume (rather correctly IMO) that a users FDN is the same everywhere. 

Is this expected, a bug, or a misconfiguration on my part?

**Comment by mmguero** [comment]
FWIW I've got the same question, about why the FDN in the `uniqueMembers` attribute of a group misses the `users` ou. In other words, when I do a listing of users, I've got `cn=sikari,ou=Administrator,ou=users,dc=example,dc=org`, but when I see him in a group it's listed as `uniqueMember: cn=sikari,ou=Administrator,dc=example,dc=org`, which is missing the `ou-users` bit. This causes some searches for group membership to fail.

**Comment by Hellhium** [comment]
The workaround I used to fix groups was to reuse the {input} parameter
Here is my currently working config for Authelia: 

```yml
  ldap:
    implementation: custom
    url: ldaps://redacted.io
    timeout: 5s
    start_tls: false
    tls:
      server_name: redacted.io
      skip_verify: true
      minimum_version: TLS1.2
    base_dn: dc=redacted,dc=io
    additional_users_dn: ou=users
    users_filter: (&({username_attribute}={input})(objectClass=posixAccount))
    username_attribute: cn
    mail_attribute: mail
    display_name_attribute: sn
    groups_filter: (&(uniqueMember=cn={input},ou=users,dc=redacted,dc=io)(objectClass=posixGroup))
    group_name_attribute: cn
    permit_referrals: false
    permit_unauthenticated_bind: false
    user: cn=redacteduser,dc=redacted,dc=io
```

And glauth.conf (backend section):
```
  baseDN = "dc=redacted,dc=io"
  nameformat = "cn"
  groupformat = "ou"
```
