### ISSUE TITLE
Empty subschema (sub)entry

### ISSUE THREAD

**Issue by yyrliu** [glauth/glauth#379]
### The issue

I'm trying to use [ldap-ui](https://github.com/dnknth/ldap-ui) as the frontend for glauth, which requires Subschema Discovery to generate the schema attributes. However, the query returned an empty schema. [The documentation](https://glauth.github.io/docs/rfcs-and-extensions.html) said that the entries in `schema/` directory are returned, however, `schema/` does not exist in `glauth/glauth-plugins` image. Probing with `ldapsearch` gave the following result:

```
~$ ldapsearch -LLL -o ldif-wrap=no -H ldap://localhost:389 -D cn=serviceuser,dc=glauth,dc=com -w mysecret -x -b "cn=schema"
dn: cn=schema
cn: schema
hasSubordinates: false
modifiersName: cn=Directory Manager
modifyTimeStamp: Mar 8, 2021, 12:46:29 PM PST (20210308204629Z)
objectclass: *

```

### My setup

Docker with `glauth/glauth-plugins` image and default [config/file](https://github.com/glauth/glauth/blob/master/v2/sample-simple.cfg).

`docker-compose.yml`
```yml
version: "3"
services:
  glauth:
    image: glauth/glauth-plugins
    container_name: glauth
    volumes:
      - ~/glauth/config/config.cfg:/app/config/config.cfg
    ports:
      - 389:389
    restart: unless-stopped

  ldap-ui:
    image: dnknth/ldap-ui
    container_name: ldap-ui
    environment:
      LDAP_URL: "ldap://glauth/"
      BASE_DN: "dc=glauth,dc=com"
      BIND_PATTERN: "cn=%s,ou=svcaccts,dc=glauth,dc=com"
      LOGIN_ATTR: "cn"
      restart: unless-stopped
```

`settings.py` of `ldap-ui` is slightly modified
```diff
USE_TLS = bool(os.environ.get('USE_TLS', LDAP_URL.startswith('ldaps://')))
INSECURE_TLS = bool(os.environ.get('INSECURE_TLS', False))

-SCHEMA_DN = 'cn=subschema'
+SCHEMA_DN = 'cn=schema'
```
