### ISSUE TITLE
Help with chained backends confg + sqlite

### ISSUE THREAD

**Issue by ericchaves** [glauth/glauth#431]
Hi, I'm trying to setup glauth with two backends: config and sqlite where the config file holds all admin/service accounts and sqlite has regular users account. 

In my local test environment I setup a config backend with two accounts: an `admin` and `serviceaccount`, and an sqlite backend with a `users` group and two users: `johndoe` and `eric`.

To test my setup Im using two ldapsearch queries (listed below):
- A search query where ldapsearch use the serviceaccount to bind and search for user names.
- A login query where ldapsearch binds with user credentials only to validate credentials.

It seems from my tests that even thou both backends are being loaded only users in backend at position 0 is actually found. When config file is at position 0, `serviceaccount` can login, can search (and find) `admin`, and `admin` can login ok, but `serviceaccount` does not find `eric` nor `johndoe`. 

When sqlite is at position 0 the opposite happens: nor `serviceaccount` or `admin` can login (users are not found) but `eric` and `johndoe` can login ok.

I'm pretty sure I'm doing something wrong but I cant figure it out. Can someone spot my error?

Query examples
- Login query for `serviceaccount`: `ldapsearch -x -LLL -H ldap://127.17.0.1:3893 -D "cn=serviceaccount,ou=svcaccts,dc=docker,dc=localhost" -w dogood -b '' -s base 'objectClass=*' 1.1`
- Login query for `admin`: `ldapsearch -x -LLL -H ldap://127.17.0.1:3893 -D "cn=admin,ou=svcaccts,dc=docker,dc=localhost" -w dogood -b '' -s base 'objectClass=*' 1.1`
- Login query for `eric`: `ldapsearch -x -LLL -H ldap://127.17.0.1:3893 -D "cn=eric,ou=users,dc=docker,dc=localhost" -w dogood -b '' -s base 'objectClass=*' 1.1`
- Login query for `johndoe`: `ldapsearch -x -LLL -H ldap://127.17.0.1:3893 -D "cn=johndoe,ou=users,dc=docker,dc=localhost" -w dogood -b '' -s base 'objectClass=*' 1.1`

- Search to query for admin: `ldapsearch -x -LLL -H ldap://127.17.0.1:3893 -D "cn=serviceuser,ou=svcaccts,dc=docker,dc=localhost" -w mysecret -b 'dc=docker,dc=localhost' '(uid=admin)'`
- Search query for johndoe: `ldapsearch -x -LLL -H ldap://127.17.0.1:3893 -D "cn=serviceuser,ou=svcaccts,dc=docker,dc=localhost" -w mysecret -b 'dc=docker,dc=localhost' '(uid=johndoe)'`

Example config file:
```toml
debug = false

# Server configuration.
[ldap]
  enabled = true
  # run on a non privileged port
  listen = "0.0.0.0:3893"
  tls = false # enable StartTLS support
  tlsCertPath = "/app/certs/ldap.docker.localhost.pem"
  tlsKeyPath = "/app/certs/ldap.docker.localhost-key.pem"

[ldaps]
  enabled = true
  listen = "0.0.0.0:3894"
  cert = "/app/certs/ldap.docker.localhost.pem"
  key = "/app/certs/ldap.docker.localhost-key.pem"

[[backends]]
  datastore = "plugin"
  plugin = "/app/sqlite.so"
  pluginhandler = "NewSQLiteHandler"
  database = "/app/config/glauth.db"
  baseDN = "dc=docker,dc=localhost"
  nameformat = "cn"
  groupformat = "ou"
  anonymousdse = false

[[backends]]
  datastore = "config"
  baseDN = "dc=docker,dc=localhost"
  nameformat = "cn"
  groupformat = "ou"
  anonymousdse = false

[tracing]
  enabled = false

[behaviors]
  IgnoreCapabilities = false
  LimitFailedBinds = true
  NumberOfFailedBinds = 3
  PeriodOfFailedBinds = 10
  BlockFailedBindsFor = 60
  PruneSourceTableEvery = 600
  PruneSourcesOlderThan = 600

[api]
  enabled = true
  internals = true # debug application performance
  tls = true # enable TLS for production!!
  listen = "0.0.0.0:5555"
  cert = "/app/certs/ldap.docker.localhost.pem"
  key = "/app/certs/ldap.docker.localhost-key.pem"

[[groups]]
  name = "svcaccts"
  gidnumber = 4000

[[users]]
  name = "serviceuser"
  mail = "serviceuser@example.com"
  uidnumber = 4001
  primarygroup = 4000
  passsha256 = "652c7dc687d98c9889304ed2e408c74b611e86a40caa51c4b43f1dd5913c5cd0" # mysecret
  [[users.capabilities]]
    action = "search"
    object = "*"

[[users]]
  name = "admin"
  mail = "admin@example.com"
  uidnumber = 4002
  primarygroup = 4000
  passsha256 = "6478579e37aff45f013e14eeb30b3cc56c72ccdc310123bcdf53e0333e3f416a" # dogood
  [[users.capabilities]]
    action = "search"
    object = "dc=docker,dc=localhost"
```
